// EOLR case data, transcribed from the "EOLR" Google Doc.
// Group notation "x/y" = number of misoriented (bad) edges on U / on D.
// Each case: variants = LR edge position pairs the algorithm covers
// (first pair is the primary diagram), alg, recognition, and
// solution / mcSolution (MC = misoriented centers) walkthroughs.

const GROUPS = [
  { id: "3/1", badEdges: ["UL", "UF", "UR", "DF"] },
  { id: "4/0", badEdges: ["UL", "UF", "UR", "UB"] },
  { id: "2o/2", badEdges: ["UL", "UR", "DF", "DB"] },
  { id: "2a/2", badEdges: ["UL", "UB", "DF", "DB"] },
  { id: "1/1", badEdges: ["UF", "DB"] },
  { id: "2o/0", badEdges: ["UF", "UB"] },
  { id: "2a/0", badEdges: ["UL", "UB"] },
  { id: "0/2", badEdges: ["DF", "DB"] },
  { id: "4/2", badEdges: ["UL", "UF", "UR", "UB", "DF", "DB"] },
];

const CASES = [
  // ---------------- 3/1 (UL/UF/UR/DF) ----------------
  {
    group: "3/1",
    name: "Stacked",
    variants: [["UF", "DF"]],
    alg: "M' U M2 U M'",
    recognition: "One LR edge is the tip of the arrow and the other is the bad edge on D.",
    mcSolution: "Do an M move to solve with misoriented centers.",
  },
  {
    group: "3/1",
    name: "Good",
    variants: [["UR", "UB"], ["UR", "DB"], ["UL", "UB"], ["UL", "DB"]],
    alg: "U M' U M",
    recognition: "One LR edge is in UL or UR and the other is in UB or DB.",
    solution: "Do an M move that puts the bottom bad edge on U. Adjust the top LR edge to be over the bottom LR edge. Do an M move to solve.",
  },
  {
    group: "3/1",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "M' U M U M U M' U",
    recognition: "Both LR edges are on D.",
    solution: "See Bad 3/1.",
    mcSolution: "Adjust the tip of the arrow to be to the side. Do an M move that puts the the good LR edge on U. Adjust the tip of the arrow to where you just moved that LR edge to. Undo the M move. Stacked 3/1 from there.",
  },
  {
    group: "3/1",
    name: "Adjacent",
    variants: [["UR", "UF"], ["UL", "UF"]],
    alg: "M' U M U M2 U M U2 M U'",
    recognition: "Both LR edges are bad and adjacent to each other.",
    solution: "See Bad 3/1.",
    mcSolution: "Adjust the non-tip LR edge to be over the bottom bad edge. Do an M move that puts the bottom bad edge on U. Do a U2. Undo the M move. Stacked 3/1 from there.",
  },
  {
    group: "3/1",
    name: "Bad",
    variants: [["UL", "UR"], ["UB", "UF"], ["UB", "DF"], ["UB", "DB"], ["UL", "DF"], ["UR", "DF"]],
    alg: "M' U M' U' M U2 M U' M2 U",
    recognition: "Not one of the above cases.",
    solution: "Do an M move that brings the misoriented D edge to U. Adjust the U face either direction. Do an M move that puts the LR edge currently in the M-slice on D. Solve LR.",
  },

  // ---------------- 4/0 (UL/UF/UR/UB) ----------------
  {
    group: "4/0",
    name: "Opposite",
    variants: [["UL", "UR"], ["UF", "UB"]],
    alg: "M' U M2 U M' U2 M U2 M",
    recognition: "LR edges are opposite each other on U.",
    mcSolution: "Adjust the LR edges to be in UF and UB and do an M'. Solve LR with misoriented centers.",
  },
  {
    group: "4/0",
    name: "Good",
    variants: [["UL", "DF"], ["UL", "DB"]],
    alg: "U M U' M U2 M U2 M",
    recognition: "One LR edge is on U and the other is on D.",
    solution: "Move the top LR edge to the side. Do M' U2 M. Good 3/1 from there.",
  },
  {
    group: "4/0",
    name: "Adjacent",
    variants: [["UL", "UF"]],
    alg: "M' U M U' M' U2 M U M' U2 M U",
    recognition: "LR edges are adjacent on U.",
    mcSolution: "Do an M move that puts the M-slice LR edge on D. Do U2 and undo the original M move. Adjacent 3/1 from there.",
  },
  {
    group: "4/0",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "U M' U2 M U2 M U M U2 M U2 M",
    recognition: "Both LR edges are on D.",
    solution: "Adjust the corners so the FD sticker matches the corners on L. Do M' U M'. UF Adjacent 1/1 from there.",
  },

  // ---------------- 2o/2 (UL/UR/DF/DB) ----------------
  {
    group: "2o/2",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "M' U M2 U M U2 M U2 M",
    recognition: "Both LR edges are on D.",
    mcSolution: "Do M' U2 M. Stacked 3/1 from there.",
  },
  {
    group: "2o/2",
    name: "Adjacent",
    variants: [["UL", "UB"], ["UR", "UF"]],
    alg: "U M' U' M' U2 M U2 M",
    recognition: "One LR edge is oriented on top and the other is misoriented on top.",
    solution: "Do M U2 M'. Good 3/1 from there.",
  },
  {
    group: "2o/2",
    name: "Decent",
    variants: [["UL", "DF"], ["UR", "DF"]],
    alg: "U M' U' M' U M U M U' M' U' M",
    recognition: "One LR edge is misoriented on U and the other is on D.",
    mcSolution: "Do an M move that brings the LR edge on bottom to the top. Do a U2. Undo the initial M move. Adjacent 3/1 from there.",
  },
  {
    group: "2o/2",
    name: "Misoriented Opposite",
    variants: [["UL", "UR"]],
    alg: "M' U M U2 M U2 M U M2",
    recognition: "The LR edges are both misoriented on top.",
    solution: "Do an M2. Bottom 2o/2 from there.",
  },
  {
    group: "2o/2",
    name: "Stacked",
    variants: [["UF", "DF"]],
    alg: "M' U M' U' M' U' M U M U2 M U2",
    recognition: "One LR edge is oriented on U and the other is on D.",
    mcSolution: "Adjust the top LR edge to be on the side. Do an M move that keeps the bottom LR edge on D, adjust the top LR edge to be over it, and undo the M move. Bottom 2o/2 from there.",
  },
  {
    group: "2o/2",
    name: "Oriented Opposite",
    variants: [["UF", "UB"]],
    alg: "U M U M' U M U M U M' U M",
    recognition: "Both LR edges are oriented.",
    solution: "Do an M', adjust the U face either direction, and undo it with an M. UF Adjacent 1/1 from there.",
  },

  // ---------------- 2a/2 (UL/UB/DF/DB) ----------------
  {
    group: "2a/2",
    name: "Best",
    variants: [["UL", "UB"]],
    alg: "M' U M U M2",
    recognition: "The LR edges are the misoriented edges on U.",
    mcSolution: "Do an M2. Stacked 3/1 from there.",
  },
  {
    group: "2a/2",
    name: "Great",
    variants: [["UF", "DF"], ["UF", "DB"], ["UR", "DF"], ["UR", "DB"]],
    alg: "U M U' M' U' M2 U",
    recognition: "One LR edge is oriented on U and the other is on D.",
    solution: "Do an M2. Good 3/1 from there.",
  },
  {
    group: "2a/2",
    name: "Opposite",
    variants: [["UL", "UR"]],
    alg: "M' U M' U M' U M' U",
    recognition: "The LR edges are opposite each other on U.",
    mcSolution: "Adjust the LR edges to be in UF and UB. Do an M move that puts the bad LR edge on D. Adjust the other bad edge to be over the bad LR edge. Repeat the initial M move. Stacked 3/1 from there.",
  },
  {
    group: "2a/2",
    name: "Stacked",
    variants: [["UL", "DF"], ["UL", "DB"], ["UB", "DF"], ["UB", "DB"]],
    alg: "M' U M' U' M U2 M U2",
    recognition: "One LR edge is misoriented on U and the other is on D.",
    solution: "Adjust the non-LR bad edge on U to be over the bottom LR edge. Do an M move that keeps the bottom LR edge on bottom, do a U2, and undo the M move. Stacked 3/1 from there.",
  },
  {
    group: "2a/2",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "U M' U' M U' M U' M",
    recognition: "Both LR edges are on D.",
    solution: "Do an M move that puts one of the bad edges on U onto D. Move the other bad edge on U over it and repeat that M move. Good 3/1 from there.",
  },
  {
    group: "2a/2",
    name: "Mixed Adjacent",
    variants: [["UL", "UF"], ["UB", "UR"]],
    alg: "U M U' M U' M2 U M U2 M",
    recognition: "One LR edge is misoriented on top and the other is adjacent to it and oriented.",
    solution: "Adjust the bad LR edge to be in the M-slice. Do an M move that keeps that puts that LR edge on bottom, do a U2, and undo that M move. Good 3/1 from there.",
  },
  {
    group: "2a/2",
    name: "Oriented Adjacent",
    variants: [["UF", "UR"]],
    alg: "M' U M' U M' U2 M U2 M U M' U",
    recognition: "The LR edges are both oriented.",
    solution: "Do an M2. Bad 3/1 from there.",
    mcSolution: "Do an M move that puts one of the bad edges on U onto D. Move the other bad edge on U over it and repeat that M move. Adjacent 3/1 from there.",
  },

  // ---------------- 1/1 (UF/DB) ----------------
  {
    group: "1/1",
    name: "Best",
    variants: [["UL", "UB"], ["UL", "DF"], ["UR", "DF"]],
    alg: "U M' U' M' U M U M",
    recognition: "Both LR edges are oriented and exactly one is in the M-slice.",
    mcSolution: "Do an M move that puts the M-slice LR edge on U. Adjust the other LR edge to be across from where you just moved the first one to. Do an M move that puts that same edge on D. Stacked 3/1 from there.",
  },
  {
    group: "1/1",
    name: "Stacked",
    variants: [["UB", "DB"]],
    alg: "U M' U' M' U' M U' M",
    recognition: "One LR edge is DB and the other is UB.",
    mcSolution: "Move the LR edge on U to the side. Do an M move that keeps the other LR edge on D. Solve LR with misoriented centers.",
  },
  {
    group: "1/1",
    name: "Good",
    variants: [["UL", "DB"], ["UR", "DB"]],
    alg: "U M U M' U M U M'",
    recognition: "One LR edge is DB and the other is not in the M-slice.",
    solution: "Do an M move that puts the M-slice LR edge on U. Adjust the other LR to be across from where you just moved the first one to. Undo the M move. Good 3/1 from there.",
  },
  {
    group: "1/1",
    name: "UF Adjacent",
    variants: [["UL", "UF"], ["UF", "UR"]],
    alg: "U M U M' U M U M",
    recognition: "One LR edge is UF and the other is adjacent to it.",
    solution: "Adjust the U layer so the good LR edge is diagonal from the bad edge on D. Do an M move that keeps the good LR edge on top. Adjust the bad LR edge to be where the good LR edge just was. Undo the M move. Good 3/1 from there.",
  },
  {
    group: "1/1",
    name: "UF Separated",
    variants: [["UF", "DF"], ["UF", "DB"]],
    alg: "U M' U M' U M U M'",
    recognition: "One LR edge is UF and the other is on D.",
    solution: "Do an M move that moves puts the top LR edge on D. Adjust the U face either direction. Undo the M move. Good 3/1 from there.",
  },
  {
    group: "1/1",
    name: "Sides",
    variants: [["UL", "UR"]],
    alg: "U M' U' M' U2 M U' M U",
    recognition: "The LR edges are in UL and UR.",
    solution: "Adjust the top bad edge to be on the side. Do an M move that keeps the bottom bad edge on D. Adjust the top bad edge to be above the bottom bad edge. Undo the M move. Good 3/1 from there.",
  },
  {
    group: "1/1",
    name: "UF Opposite",
    variants: [["UF", "UB"]],
    alg: "M' U M' U' M U' M' U2 M U M' U2",
    recognition: "The LR edges are in UF and UB.",
    mcSolution: "Do an M move that puts the bad LR edge on D. Do a U and undo the M move. Adjacent 3/1 from there.",
  },
  {
    group: "1/1",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "M' U M U M' U M U M' U M' U",
    recognition: "Both LR edges are on D.",
    mcSolution: "Do an M move that keeps the bad LR edge on D. Do a U and undo the M move. Great 2a/2 from there.",
  },
  {
    group: "1/1",
    name: "Bad",
    variants: [["UB", "DF"]],
    alg: "M U' M U' M U2 M U' M' U' M U",
    recognition: "Both LR edges are oriented on the M slice.",
    solution: "Adjust the top bad edge to be on the side. Do an M move that keeps the bottom bad edge on D. Adjust the top bad edge to be above the bottom bad edge. Undo the M move. Adjacent 3/1 from there.",
  },

  // ---------------- 2o/0 (UF/UB) ----------------
  {
    group: "2o/0",
    name: "Best",
    variants: [["UL", "DF"], ["UR", "DF"]],
    alg: "U M' U M' U' M U M'",
    recognition: "One LR edge is on bottom and the other is oriented on top.",
    mcSolution: "Do an M move to put the bottom LR edge on top. Adjust the other LR edge to replace it, then undo that M move. Stacked 3/1 from there.",
  },
  {
    group: "2o/0",
    name: "Misoriented",
    variants: [["UF", "UB"]],
    alg: "U M' U M U' M' U M",
    recognition: "Both LR edges are misoriented.",
    solution: "Do M' U M. Good 3/1 from there.",
  },
  {
    group: "2o/0",
    name: "Stacked",
    variants: [["UF", "DF"], ["UF", "DB"]],
    alg: "U M' U' M' U' M U M'",
    recognition: "One LR edge is on D and the other is misoriented.",
    solution: "Adjust the top LR edge to be over the bottom one. Do an M to put both on D, do a U', and undo the M move. Good 3/1 from there.",
  },
  {
    group: "2o/0",
    name: "Adjacent",
    variants: [["UF", "UL"], ["UF", "UR"]],
    alg: "U M' U M U M' U' M",
    recognition: "One LR edge is on D and the other is misoriented.",
    solution: "Do an M move that keeps the bad LR edge on top. Adjust the U face to replace it with the other LR edge. Undo the M move. Good 3/1 from there.",
  },
  {
    group: "2o/0",
    name: "Opposite",
    variants: [["UL", "UR"]],
    alg: "M' U M' U M' U2 M U M U M",
    recognition: "Both LR edges are oriented on top.",
    mcSolution: "Adjust the LR edges to be in the M slice. Do M' U2 M. Best 2o/0 from there.",
  },
  {
    group: "2o/0",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "U' M U' M' U' M' U2 M U' M U' M",
    recognition: "Both LR edges are on bottom.",
    mcSolution: "Adjust the bad edges to be in UL and UR. Do M U2 M'. Best 2o/0 from there.",
  },

  // ---------------- 2a/0 (UL/UB) ----------------
  {
    group: "2a/0",
    name: "Best",
    variants: [["UL", "UF"], ["UB", "UR"]],
    alg: "M' U M' U2 M U' M2 U M U",
    recognition: "One LR edge is misoriented and the other is adjacent to it and oriented.",
    solution: "Adjust the good LR edge to be in the M-slice. Do an M move that keeps it on U. Move the other LR edge to that new location and repeat the first M move. Good 3/1 from there.",
    mcSolution: "Adjust the bad LR edge to be in the M-slice. Do an M move to put it on D. Solve LR with misoriented centers.",
  },
  {
    group: "2a/0",
    name: "Stacked",
    variants: [["UF", "DF"], ["UF", "DB"], ["UR", "DF"], ["UR", "DB"]],
    alg: "M' U M U' M' U' M' U' M2",
    recognition: "One LR edge is on D and the other is oriented on U.",
    solution: "Adjust the top LR edge to be in diagonal from the bottom one. Do an M move that keeps it on top. Move it to be opposite of the bad edge still on U, then undo that M move. Good 3/1 from there.",
  },
  {
    group: "2a/0",
    name: "Good",
    variants: [["UL", "DF"], ["UL", "DB"], ["UB", "DF"], ["UB", "DB"]],
    alg: "U M2 U M' U' M U2 M U' M",
    recognition: "One LR is on D and the other is misoriented on U.",
    solution: "Adjust the non-LR bad edge to be diagonal from the LR edge on bottom. Do an M to bring it to the bottom, move the top LR edge over it, and undo that M move. Good 3/1 from there.",
  },
  {
    group: "2a/0",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "U M' U M' U2 M U M' U",
    recognition: "Both LR edges are on the bottom.",
    solution: "Do an M move that puts one of the bad edges on D. Adjust the other bad edge to be over it. Undo the original M move. Good 3/1 from there.",
  },
  {
    group: "2a/0",
    name: "Oriented Adjacent",
    variants: [["UF", "UR"]],
    alg: "M' U M U M' U M U M U2 M",
    recognition: "Both LR edges are oriented on U.",
    mcSolution: "Do an M move to put one of the LR edges on D, then a U2, then undo that M move. Best 1/1 from there.",
  },
  {
    group: "2a/0",
    name: "Opposite",
    variants: [["UL", "UR"], ["UF", "UB"]],
    alg: "M' U M U' M' U' M U' M' U' M U",
    recognition: "One LR edge is misoriented and the other is opposite of it.",
    mcSolution: "Adjust the LR edges to both be in the M-slice. Do an M move to put the good LR edge on D. Adjust the non-LR bad edge to be over it and undo the first M move. Best 1/1 from there.",
  },
  {
    group: "2a/0",
    name: "Misoriented Adjacent",
    variants: [["UL", "UB"]],
    alg: "M' U M' U M U M' U' M U M U",
    recognition: "Both LR edges are misoriented.",
    solution: "Do an M2. UF Separated 1/1 from there.",
    mcSolution: "Do an M move that keeps both LR edges on top. Move the LR edge not in the M-slice to where the other LR edge now is. Undo the original M move. Best 1/1 from there.",
  },

  // ---------------- 0/2 (DF/DB) ----------------
  {
    group: "0/2",
    name: "Adjacent",
    variants: [["UL", "UF"], ["UL", "UB"]],
    alg: "M' U M' U' M U M U",
    recognition: "The LR edges are on U and adjacent.",
    mcSolution: "Do an M move that keeps the M-slice LR edge on U. Adjust the other LR to that position. Repeat the initial M move. Stacked 3/1 from there.",
  },
  {
    group: "0/2",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "U M U M' U' M U M",
    recognition: "Both LR edges are on D.",
    solution: "Adjust the corners so the LR stickers are on L or R. Do M', bring the corners that match the DF sticker (now in FU), and repeat the M'. Good 3/1 from there.",
  },
  {
    group: "0/2",
    name: "Good",
    variants: [["UL", "DF"], ["UL", "DB"], ["UF", "DF"], ["UF", "DB"]],
    alg: "U M U' M' U' M U M",
    recognition: "One LR edge is on U and the other is on D.",
    solution: "Adjust the top LR edge to be on the side. Do an M move that puts the bottom LR edge on top. Adjust the other LR edge to be in that position. Repeat the first M move. Good 3/1 from there.",
  },
  {
    group: "0/2",
    name: "Opposite",
    variants: [["UL", "UR"]],
    alg: "M' U M' U' M U2 M U M' U M",
    recognition: "The LR edges are opposite on U.",
    mcSolution: "Adjust the LR edges to be in UL and UR. Do M' U M. Stacked 2a/2 from there.",
  },

  // ---------------- 4/2 (UL/UF/UR/UB/DF/DB) ----------------
  {
    group: "4/2",
    name: "Adjacent",
    variants: [["UL", "UF"], ["UL", "DF"], ["UL", "DB"]],
    alg: "M' U M U' M' U' M U2 M U M",
    recognition: "The LR edges are adjacent on U or one is on U and the other is on D.",
    mcSolution: "If one LR edge is on bottom, adjust the U face so that the top LR edge is not in the M slice. Do an M move that puts the M-slice LR edge on D. Adjust the top LR edge to be diagonally opposite the other. Do an M move to keep the top LR edge on top, adjust the U face either direction, then undo that last M move. Solve LR with misoriented centers.",
  },
  {
    group: "4/2",
    name: "Opposite",
    variants: [["UL", "UR"]],
    alg: "U M' U' M' U2 M' U' M U' M' U' M",
    recognition: "The LR edges are opposite on U.",
    solution: "Adjust the LR edges to both be in the M-slice. Do M' U M'. Good 1/1 from there.",
  },
  {
    group: "4/2",
    name: "Bottom",
    variants: [["DF", "DB"]],
    alg: "U M' U' M' U2 M' U' M U' M' U' M'",
    recognition: "The LR edges are both on D.",
    solution: "Adjust the corners so the DF sticker matches the F corners. Do M' U M. Good 1/1 from there.",
  },
];
